import { readFile } from 'node:fs/promises';
import path from 'node:path';

const API_PAGE_REGEX = /<APIPage\b([^>]*)\/>/g;

/** Per-document cache — copy-markdown only loads the files referenced on each page. */
const documentCache = new Map<string, OpenAPIDocument>();

const GENERATED_COMMENT_REGEX =
  /\{\/\*\s*This file was generated by Fumadocs[\s\S]*?\*\/\}\s*/g;

interface OperationItem {
  path: string;
  method: string;
}

interface WebhookItem {
  name: string;
  method: string;
}

interface APIPageProps {
  document: string;
  operations?: OperationItem[];
  webhooks?: WebhookItem[];
}

interface OpenAPIParameter {
  name: string;
  in: string;
  required?: boolean;
  description?: string;
  schema?: { type?: string };
}

interface OpenAPIOperation {
  operationId?: string;
  summary?: string;
  description?: string;
  parameters?: OpenAPIParameter[];
  security?: Record<string, string[]>[];
  requestBody?: {
    description?: string;
    content?: Record<string, { schema?: unknown }>;
  };
  responses?: Record<
    string,
    {
      description?: string;
      content?: Record<string, { schema?: unknown }>;
    }
  >;
}

interface OpenAPIDocument {
  servers?: { url?: string }[];
  security?: Record<string, string[]>[];
  paths?: Record<string, Record<string, OpenAPIOperation | undefined>>;
  webhooks?: Record<string, Record<string, OpenAPIOperation | undefined>>;
  components?: {
    securitySchemes?: Record<
      string,
      {
        type?: string;
        scheme?: string;
        description?: string;
      }
    >;
  };
}

function extractJsxProp(attrs: string, name: string): unknown | undefined {
  const key = `${name}=`;
  const idx = attrs.indexOf(key);
  if (idx === -1) return undefined;

  let start = idx + key.length;
  if (attrs[start] !== '{') return undefined;

  let depth = 0;
  let end = start;
  for (; end < attrs.length; end++) {
    if (attrs[end] === '{') depth++;
    else if (attrs[end] === '}') {
      depth--;
      if (depth === 0) break;
    }
  }

  // JSX expression: document={"path"} → inner is "path", not {"path"}
  const inner = attrs.slice(start + 1, end).trim();
  return JSON.parse(inner);
}

function parseAPIPageProps(attrs: string): APIPageProps | null {
  const document = extractJsxProp(attrs, 'document');
  if (typeof document !== 'string') return null;

  const operations = extractJsxProp(attrs, 'operations') as
    | OperationItem[]
    | undefined;
  const webhooks = extractJsxProp(attrs, 'webhooks') as
    | WebhookItem[]
    | undefined;

  if (!operations?.length && !webhooks?.length) return null;

  return { document, operations, webhooks };
}

function formatParameter(param: OpenAPIParameter): string {
  const required = param.required ? 'Yes' : 'No';
  const type = param.schema?.type ?? 'unknown';
  return `| ${param.name} | ${param.in} | ${required} | ${type} | ${param.description ?? ''} |`;
}

function formatSecurity(
  security: Record<string, string[]>[] | undefined,
  schemes?: Record<
    string,
    { type?: string; scheme?: string; description?: string }
  >
): string[] {
  if (!security?.length || !schemes) return [];

  const lines: string[] = [];
  for (const req of security) {
    for (const [name] of Object.entries(req)) {
      const scheme = schemes[name];
      if (!scheme) continue;

      if (scheme.type === 'http' && scheme.scheme === 'bearer') {
        lines.push(
          `- **${name}**: Bearer Token (\`Authorization: Bearer <token>\`)`
        );
        if (scheme.description) lines.push(`  ${scheme.description.trim()}`);
      } else {
        lines.push(`- **${name}**: ${scheme.type ?? 'unknown'}`);
        if (scheme.description) lines.push(`  ${scheme.description.trim()}`);
      }
    }
  }
  return lines;
}

function safeStringify(value: unknown): string {
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return '/* schema could not be serialized */';
  }
}

async function loadOpenAPIDocument(
  documentPath: string
): Promise<OpenAPIDocument | null> {
  const cached = documentCache.get(documentPath);
  if (cached) return cached;

  try {
    const filePath = path.join(process.cwd(), documentPath);
    const raw = await readFile(filePath, 'utf8');
    const doc = JSON.parse(raw) as OpenAPIDocument;
    documentCache.set(documentPath, doc);
    return doc;
  } catch {
    return null;
  }
}

function formatRequestBody(
  body: OpenAPIOperation['requestBody']
): string[] {
  if (!body) return [];

  const lines: string[] = ['### Request Body', ''];
  if (body.description) lines.push(body.description, '');

  for (const [mediaType, content] of Object.entries(body.content ?? {})) {
    lines.push(`**Content-Type:** \`${mediaType}\``);
    if (content.schema) {
      lines.push(
        '```json',
        safeStringify(content.schema),
        '```',
        ''
      );
    }
  }
  return lines;
}

function formatResponses(
  responses: OpenAPIOperation['responses']
): string[] {
  if (!responses) return [];

  const lines: string[] = ['### Responses', ''];
  for (const [status, response] of Object.entries(responses)) {
    lines.push(`#### ${status} - ${response.description ?? 'Response'}`, '');

    for (const [mediaType, content] of Object.entries(
      response.content ?? {}
    )) {
      lines.push(`**Content-Type:** \`${mediaType}\``);
      if (content.schema) {
        lines.push(
          '```json',
          safeStringify(content.schema),
          '```',
          ''
        );
      }
    }
  }
  return lines;
}

function operationToMarkdown(
  doc: OpenAPIDocument,
  path: string,
  method: string
): string | null {
  const pathItem = doc.paths?.[path];
  if (!pathItem) return null;

  const operation = pathItem[method];
  if (!operation) return null;

  const methodUpper = method.toUpperCase();
  const serverUrl = doc.servers?.[0]?.url ?? '';

  const lines: string[] = [
    `## ${methodUpper} ${path}`,
    '',
    `**Server:** \`${serverUrl}\``,
  ];

  if (operation.operationId)
    lines.push(`**Operation ID:** \`${operation.operationId}\``);
  lines.push('');

  if (operation.summary) lines.push(`**Summary:** ${operation.summary}`, '');
  if (operation.description) lines.push(operation.description, '');

  if (operation.parameters?.length) {
    lines.push(
      '### Parameters',
      '',
      '| Name | In | Required | Type | Description |',
      '| --- | --- | --- | --- | --- |',
      ...operation.parameters.map(formatParameter),
      ''
    );
  }

  const securityLines = formatSecurity(
    operation.security ?? doc.security,
    doc.components?.securitySchemes
  );
  if (securityLines.length) {
    lines.push('### Authorization', '', ...securityLines, '');
  }

  lines.push(...formatRequestBody(operation.requestBody));
  lines.push(...formatResponses(operation.responses));

  return lines.join('\n');
}

function webhookToMarkdown(
  doc: OpenAPIDocument,
  name: string,
  method: string
): string | null {
  const webhook = doc.webhooks?.[name];
  if (!webhook) return null;

  const operation = webhook[method];
  if (!operation) return null;

  const methodUpper = method.toUpperCase();
  const lines: string[] = [`## Webhook: ${name} (${methodUpper})`, ''];

  if (operation.summary) lines.push(`**Summary:** ${operation.summary}`, '');
  if (operation.description) lines.push(operation.description, '');

  lines.push(...formatRequestBody(operation.requestBody));
  lines.push(...formatResponses(operation.responses));

  return lines.join('\n');
}

async function expandAPIPage(props: APIPageProps): Promise<string> {
  const doc = await loadOpenAPIDocument(props.document);
  if (!doc) {
    return `<!-- OpenAPI document not found: ${props.document} -->`;
  }
  const sections: string[] = [];

  for (const item of props.operations ?? []) {
    const section = operationToMarkdown(doc, item.path, item.method);
    if (section) sections.push(section);
  }

  for (const item of props.webhooks ?? []) {
    const section = webhookToMarkdown(doc, item.name, item.method);
    if (section) sections.push(section);
  }

  return sections.join('\n\n');
}

export async function expandAPIPagesInMarkdown(
  markdown: string
): Promise<string> {
  const cleaned = markdown.replace(GENERATED_COMMENT_REGEX, '');

  const matches = [...cleaned.matchAll(API_PAGE_REGEX)];
  if (matches.length === 0) return cleaned;

  let result = cleaned;
  for (const match of matches) {
    const fullTag = match[0];
    const attrs = match[1];
    const props = parseAPIPageProps(attrs);

    const replacement = props ? await expandAPIPage(props) : fullTag;

    result = result.replace(fullTag, replacement);
  }

  return result.trim();
}
